# config.yml

model_type:
  gric
# mdoel args
model:        
  image_channel: 3
  image_weight: 512
  image_height: 512
  patch_size: 2
  embedding_dim: 40
  window_size: 4
  head_num: 1
  shift_size: 0
  out_channel_m: 192
  out_channel_n: 128
  transfomer_head: 2
  transfomer_blocks: 3
  drop_prob: 0.1
  lamda: 0.0932
  finetune_model_dir: "./saved_model/fbr/imagenet/gric/0.18"  
  device: cuda   

# trainning args
traininng:
  batch_size: 2               
  epochs: 100          
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0.0001
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  compression
dataset:
  target_width: 512
  target_height: 512
  train_data_path: imagenet_train/train.jsonl
  test_data_path: imagenet_train/test.jsonl
  valid_data_path: imagenet_train/val.jsonl



logging:
  eval_interval: 100           
  save_dir: "./saved_model/fbr/imagenet/gric"   