# config.yml

model_type:
  stfcqvr
# mdoel args
model:        
  image_channel: 3
  image_weight: 256
  image_height: 256
  patch_size: 2
  embedding_dim: 40
  out_channel_m: 192
  out_channel_n: 128
  time_dim: 32
  stage: 1
  device: cuda   

# trainning args
traininng:
  batch_size: 2               
  epochs: 500          
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0.0001
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  compression
dataset:
  target_width: 256
  target_height: 256
  train_data_path: imagenet_train/train.jsonl
  test_data_path: imagenet_train/test.jsonl
  valid_data_path: imagenet_train/val.jsonl



logging:
  eval_interval: 100        
  save_dir: "./saved_model/vbr/stfcqvr-imagenet"   