# config.yml

model_type:
  vicqvrf
# mdoel args
model:        
  image_channel: 3
  image_weight: 512
  image_height: 512
  out_channel_m: 192
  out_channel_n: 128
  stage: 2
  device: cuda   

# trainning args
traininng:
  batch_size: 2               
  epochs: 1000          
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0.0001   
  clip_max_norm: 0.5
  factor: 0.3
  patience: 20         
  device: cuda

dataset_type:
  eticn
dataset:
  target_width: 512
  target_height: 512
  train_data_path: camvid_train/train.jsonl
  test_data_path: camvid_train/test.jsonl
  valid_data_path: camvid_train/val.jsonl



logging:
  eval_interval: 10    
  save_dir: "./saved_model/vicvbr"   